core/urls.py
from leads.views import LandingView, SignUpView
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls')),
    path('', LandingView.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'), 
]

leads/urls.py
from django.urls import path
from .views import (
    IndexView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView, 
    LeadDeleteView 
) 

app_name = 'leads'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', LeadDetailView.as_view(), name='detail'),
    path('create/', LeadCreateView.as_view(), name='create'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='delete'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    # add to settings AUTH_USER_MODEL = 'leads.User'
    pass
    def __str__(self):
        return self.email

class Lead(models.Model):
    # CHOICE_SOURCE = (
    #     ('YouTube', 'YouTube'),
    #     ('Google', 'Google'),
    #     ('Facebook', 'Facebook'),
    #     ('Twitter', 'Twitter'),
    #     )
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    age             = models.IntegerField(default=0)
    agent           = models.ForeignKey("Agent", on_delete=models.CASCADE)
    # phoned          = models.BooleanField(default=False)
    # source          = models.CharField(choices=CHOICE_SOURCE, max_length=50)
    # profile_picture = models.ImageField(blank=True, null=True, upload_to=None, height_field=None, 
    #                                             width_field=None, max_length=None)
    # special_files   = models.FileField(blank=True, null=True, upload_to=None, max_length=100)                                                
    def __str__(self):
         return (f"{self.first_name} {self.last_name}")


class Agent(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.email

leads/forms.py
from django import forms
from .models import Lead
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()






class LeadForm(forms.Form):
    first_name      = forms.CharField()
    last_name       = forms.CharField()
    age             = forms.IntegerField()
    # agent           = forms.ForeignKey()

    
class CustomUserCreationForm(UserCreationForm):
    class Meta: 
        model = User
        fields = ('username',)
        field_classes = {'username' : UsernameField}


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',     
            'last_name',       
            'age',             
            'agent',           

        )

    

leads/views.py
from django.shortcuts import (render, redirect, reverse) 
# from django.urls import 
from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm
from django.views.generic import (
    TemplateView, 
    ListView, 
    DetailView, 
    CreateView, 
    UpdateView, 
    DeleteView,
    CreateView
    ) 


class SignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login') 

class LandingView(TemplateView):
    template_name = 'landing.html'


class IndexView(ListView):
    template_name = 'leads/index.html'
    queryset = Lead.objects.all()
    context_object_name = 'leads'
    # default is object_list


class LeadDetailView(DetailView):
    template_name = 'leads/detail.html'
    queryset = Lead.objects.all()
    context_object_name = 'lead'


class LeadCreateView(CreateView):
    template_name = 'leads/create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:index') 


class LeadUpdateView(UpdateView):
    template_name = 'leads/update.html'
    queryset = Lead.objects.all()
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:index')


class LeadDeleteView(DeleteView):
    template_name = 'leads/delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:index')

leads/templates/landing.html
{% extends 'leads/base.html' %} {% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="text-center mb-20">
      <h1
        class="sm:text-3xl text-2xl font-medium text-center title-font text-gray-900 mb-4"
      >
        Raw Denim Heirloom Man Braid
      </h1>
      <p class="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto">
        Blue bottle crucifix vinyl post-ironic four dollar toast vegan
        taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi
        pug.
      </p>
    </div>
    <div class="flex flex-wrap lg:w-4/5 sm:mx-auto sm:mb-2 -mx-2">
      <div class="p-2 sm:w-1/2 w-full">
        <div class="bg-gray-100 rounded flex p-4 h-full items-center">
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="3"
            class="text-pink-500 w-6 h-6 flex-shrink-0 mr-4"
            viewBox="0 0 24 24"
          >
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
            <path d="M22 4L12 14.01l-3-3"></path>
          </svg>
          <span class="title-font font-medium">Authentic Cliche Forage</span>
        </div>
      </div>
      <div class="p-2 sm:w-1/2 w-full">
        <div class="bg-gray-100 rounded flex p-4 h-full items-center">
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="3"
            class="text-pink-500 w-6 h-6 flex-shrink-0 mr-4"
            viewBox="0 0 24 24"
          >
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
            <path d="M22 4L12 14.01l-3-3"></path>
          </svg>
          <span class="title-font font-medium">Kinfolk Chips Snackwave</span>
        </div>
      </div>
      <div class="p-2 sm:w-1/2 w-full">
        <div class="bg-gray-100 rounded flex p-4 h-full items-center">
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="3"
            class="text-pink-500 w-6 h-6 flex-shrink-0 mr-4"
            viewBox="0 0 24 24"
          >
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
            <path d="M22 4L12 14.01l-3-3"></path>
          </svg>
          <span class="title-font font-medium">Coloring Book Ethical</span>
        </div>
      </div>
      <div class="p-2 sm:w-1/2 w-full">
        <div class="bg-gray-100 rounded flex p-4 h-full items-center">
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="3"
            class="text-pink-500 w-6 h-6 flex-shrink-0 mr-4"
            viewBox="0 0 24 24"
          >
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
            <path d="M22 4L12 14.01l-3-3"></path>
          </svg>
          <span class="title-font font-medium">Typewriter Polaroid Cray</span>
        </div>
      </div>
    </div>
    <button
      class="flex mx-auto mt-16 text-white bg-pink-500 border-0 py-2 px-8 focus:outline-none hover:bg-pink-600 rounded text-lg"
    >
      Button
    </button>
  </div>
</section>
{% endblock content %}

leads/templates/leads/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include 'leads/navbar.html' %}
    {% block content %}
    {% endblock content %}
</body>
</html>

leads/templates/leads/create.html
{% extends "leads/base.html" %} {% block content %}
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
      <h1
        class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900"
      >
        Create a Lead
      </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        Remember to assign the lead while creating it.
      </p>
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2">
        <form method="POST">
          {% csrf_token %} {{form.as_p}}
          <div class="p-2 w-full">
            <button
              type="submit"
              class="flex-shrink-0 text-white bg-pink-500 border-0 py-2 px-8 
              focus:outline-none hover:bg-pink-600 rounded text-lg mt-10 sm:mt-0"
            >
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/delete.html
{% extends "leads/base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-12">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
            Please confim you want to delete Lead {{lead.first_name}} {{lead.last_name}}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button 
            class="flex-shrink-0 text-white bg-pink-500 border-0 py-2 px-8 
            focus:outline-none 
            hover:bg-pink-600 rounded text-lg mt-10 sm:mt-0" type="submit">Delete</button>
        </form>
        </p>
      </div>
    </div>
  </section>


{% endblock content %}

leads/templates/leads/detail.html
{% extends "leads/base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div class="container flex flex-wrap px-5 py-24 mx-auto items-center">
    <div
      class="md:w-1/2 md:pr-12 md:py-8 md:border-r md:border-b-0 mb-10 md:mb-0 pb-10 border-b border-gray-200"
    >
      <h1
        class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900"
      >
        {{ lead.first_name }} {{ lead.last_name }}
      </h1>
      <p class="leading-relaxed text-base">
        Locavore cardigan small batch roof party blue bottle blog meggings
        sartorial jean shorts kickstarter migas sriracha church-key synth
        succulents. Actually taiyaki neutra, distillery gastropub pok pok ugh.
      </p>

      <a
        href="{% url 'leads:update' lead.pk %}"
        class="text-pink-500 inline-flex items-center mt-4"
        >Update
        <svg
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          class="w-4 h-4 ml-2"
          viewBox="0 0 24 24"
        >
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      <a
        href="{% url 'leads:delete' lead.pk %}"
        class="text-pink-500 inline-flex items-center mt-4"
        >Delete
        <svg
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          class="w-4 h-4 ml-2"
          viewBox="0 0 24 24"
        >
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
    <div class="flex flex-col md:w-1/2 md:pl-12">
      <h2
        class="title-font font-semibold text-gray-800 tracking-wider text-sm mb-3"
      >
        CATEGORIES
      </h2>
      <nav class="flex flex-wrap list-none -mb-1">
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">First Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Second Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Third Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Fifth Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Sixth Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Seventh Link</a>
        </li>
        <li class="lg:w-1/3 mb-1 w-1/2">
          <a class="text-gray-600 hover:text-gray-800">Eighth Link</a>
        </li>
      </nav>
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/index.html
{% extends "leads/base.html" %}
{% block content %}
<a href="{% url 'leads:create' %}">Create a Lead</a>

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="flex flex-wrap -m-4">
            {% comment %} start {% endcomment %}
            {% for lead in leads %}

            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div
                        class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                            <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                            <circle cx="12" cy="7" r="4"></circle>
                        </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">1</h2>
                        <p class="leading-relaxed text-base">{{ lead.age }}
                            {{ lead.agent }}post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice
                            poutine.</p>
                        <a href="{% url 'leads:detail' lead.pk %}"
                            class="mt-3 text-pink-500 inline-flex items-center">Details
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% comment %} end {% endcomment %}
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/navbar.html
<header class="text-gray-600 body-font">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >
    <a
      href="{% url 'landing-page'%}"
      class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-10 h-10 text-white p-2 bg-pink-500 rounded-full"
        viewBox="0 0 24 24"
      >
        <path
          d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
        ></path>
      </svg>
      <span class="ml-3 text-xl">CRM</span>
    </a>
    <nav
      class="md:ml-auto flex flex-wrap items-center text-base justify-center"
    >
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
      <a href="{% url 'login' %}" class="mr-5 hover:text-gray-900">Log In</a>
      {% endif %} {% if request.user.is_authenticated %} You are logged in {{
      user.username }}
      <a href="{% url 'leads:index'%}" class="ml-3 mr-5 hover:text-gray-900"
        >Leads</a
      >
      <a href="{% url 'logout' %}" class="ml-3 mr-5 hover:text-gray-900"
        >Log Out</a
      >
      {% endif %}
    </nav>
  </div>
</header>

leads/templates/leads/update.html
{% extends "leads/base.html" %} {% block content %}
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
      <h1
        class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900"
      >
        Updating Lead: {{ lead.first_name}} {{ lead.last_name}}
      </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        This lead is assignd to: {{ lead.agent }}
      </p>
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2">
        <form method="POST">
          {% csrf_token %} {{form.as_p}}
          <div class="p-2 w-full">
            <button
              type="submit"
              class="flex-shrink-0 text-white bg-pink-500 border-0 py-2 px-8 focus:outline-none hover:bg-pink-600 rounded text-lg mt-10 sm:mt-0"
            >
              Update
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}